name: Issues Output
on: issues
  types: [opened, edited, deleted]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event details
        run: echo "${{ toJSON(github.event) }}"